### ISSUE TITLE
how to make the cam stay online

### ISSUE THREAD

**Issue by eihns** [acolomba/blackvuesync#2]
I wonder when i pull my car into the garage and shut it off... wont the camera turn off and it cant be downloaded? Is there a way to keep the camera on for some minutes after shutting the car off? How you do it?

**Comment by acolomba** [comment]
The camera has to be hardwired to something that continues to give it power for a time period.

I use

**Comment by eihns** [comment]
that first link is the same as the second and i cant really find it thru google.

**Comment by acolomba** [comment]
fixed the first link

**Comment by eihns** [comment]
Thank you very much.

Im absolulty new to this car stuff, so i will take your information to my car dealer to install it.

I really want a set and forget solution. So i could just let parking mode on for forever, right? Cant i just say like stay on for half an hour... or something like this?

**Comment by acolomba** [comment]
Yes, the kits have a timer to leave the camera on for a set period of time. You'll want to set a time sufficient to download new recordings. That time depends on driving habits, recording quality and the throughput through the Wi-Fi connection.

I think I'll take this opportunity to add some documentation to that effect.

**Comment by eihns** [comment]
Usually it shouldnt be much. Wifi should be good at that spot. Also it should resume downloads, right?

How long does the download takes for you?
