### ISSUE TITLE
New file types aren't deleted by --keep switch

### ISSUE THREAD

**Issue by adamcurrey** [acolomba/blackvuesync#4]
Thank you very much for a great tool!

Looks like 1.8 added support for downloading the new files that Blackvue's May 2021 firmware update added, but not for cleaning them up with the --keep switch.  I have the following left behind:

I
IF
IR
A
AF
AR
T
TF
TR

(EG 20210525_175137_**AF**.mp4)

Thanks,
Adam

**Comment by acolomba** [comment]
Thank you, this was an oversight. I'll take care of this over the weekend. The files will be deleted once the new version runs.

**Comment by adamcurrey** [comment]
Wonderful, thank you.

**Comment by adamcurrey** [comment]
Can confirm issue resolved.

Thank you, love your work!
