### ISSUE TITLE
Feature request: newest to oldest priority

### ISSUE THREAD

**Issue by Robpol86** [acolomba/blackvuesync#5]
Currently `time` downloads oldest to newest. It would be nice to have an additional priority option for reverse chronological order, newest to oldest.

Use case is I have a Raspberry Pi in my car that backs up footage every minute in case someone breaks in and steals the camera.

**Comment by acolomba** [comment]
Yes, I can do that.

In the meantime, if you don't want to wait, you ought to be able change this line in the Python script from:

```python
    recordings.sort(key=sort_key)
```

to:

```python
    recordings.sort(key=sort_key, reverse=True)
```

Then use the default priority.

**Comment by acolomba** [comment]
added a `--priority rdate` option that downloads from newest to oldest (and fixed docs, the original option was `date`, not `time`)
