### ISSUE TITLE
No GPS data for P|I recordings

### ISSUE THREAD

**Issue by Sungray** [acolomba/blackvuesync#9]
` if recording.type in ("N", "E", "M"):`

This avoids importing .gps files for some recordings.
Not having any .gps file is problematic for the popular Dashcam Viewer. It requires .gps data on all files to work properly (bug on their part).
I suppose importing these .gps files was caising issues since you added this condition, but in that case, would it be possible to add something like this?

```
if recording.type in ("P", "I"):
    touch recording.base_filename+".gps"
```

not sure if there are other events than N, E, M, P, I.

**Comment by acolomba** [comment]
I'm sorry, i had not noticed this issue had been created.

I was not aware of the camera producing gps files for parking and impact, but I could have been mistaken.

Will follow-up shortly.

**Comment by acolomba** [comment]
Many thanks for this bug report. should be fixed now.
